Fix bug in stable function warning in column prop
material-table-core/core pull request #325
Opened 2021-08-27 08:23 UTC by tamilarasu602

## Related Issue

Fixes issues mentioned in https://github.com/material-table-core/core/pull/259#issuecomment-906657198

## Description

- This PR fixes bug with the column warning check which is run even when the column prop is not updated.
- The fix ensures the column prop need to be changed for the warning check to run.

## Related PRs

| Branch              | PR       |
| ------------------- | -------- |
| Data Id | [link](https://github.com/material-table-core/core/pull/259) |

2021-08-27 16:33 UTC, matthewoestreich approved these changes
Thank you so very much @tamilarasu602 !

2021-08-27 16:34 UTC, Domino987 requested changes

2021-08-27 16:34 UTC, Domino987 commented on src/material-table.js
> +    let propsChanged = columnPropsChanged;
let propsChanged = columnPropsChanged || ...

Would this lead to the same code without redundant wrapper?

2021-08-27 16:49 UTC, tamilarasu602 commented on src/material-table.js
> +    let propsChanged = columnPropsChanged;
I have left the value of the `propsChanged` same as before, to not change the rest of the logic in `componentDidUpdate`

Added the `columnPropsChanged` as a necessary condition to run the `columnsEqual` check happening in lines `197-221`

2021-08-31 17:24 UTC, oze4 commented
@Domino987 we good to merge this?

2021-08-31 17:30 UTC, Domino987 commented
No I would like to change the thing I mentioned but I will fix this tomorrow

2021-09-01 08:10 UTC, Domino987 approved these changes

2021-09-01 08:10 UTC, merged

2021-09-20 09:34 UTC, oscar-b commented
@Domino987 Any idea when this will find itself into a release?

2021-09-20 09:35 UTC, Domino987 commented
I will be back tonight. So I hope someday tomorrow