Add clear criteria
material-table-core/core pull request #576
Opened 2022-06-29 02:40 UTC by ckchiu2

## Description

Added and exposed clearCriteria() from MaterialTable. Use the following code to clear existing criteria, including filters, sorts and search text. Page will be reset to 0.

`
tableRef.current.clearCriteria()
`

## Impacted Areas in Application

<MaterialTable />
data-manager.js

2022-06-30 15:06 UTC, Domino987 requested changes
Can we not change the prettier though this PR and only change the code that is required here?

2022-06-30 15:06 UTC, Domino987 commented on types/index.d.ts
> +  clearCriteria: () => void;
This needs to be at the MaterialTableProps level to be consistent with everything

2022-06-30 18:33 UTC, ckchiu2 commented
If you mean to revert auto formatted code like this, it is fine.
I don't know why it is auto-formatted though.

2022-07-01 15:54 UTC, Domino987 commented
> If you mean to revert auto formatted code like this, it is fine. I don't know why it is auto-formatted though.

Prettier most likely, but ok

2022-07-03 15:51 UTC, ckchiu2 commented
Sorry but what do you mean by prop types?
The added type is for the ref, i.e. the MaterialTable object, not for the props.

2022-07-06 14:16 UTC, Domino987 approved these changes

2022-07-06 14:16 UTC, merged